AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cost-alert

  Sample SAM Template for cost-alert

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 100
    Environment:
      Variables:
        MATTERMOST_HOOK: 'https://example.com/hooks/xxxxxxxxxx'

Resources:
  CostUsageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Policies:
      - Statement:
        - Sid: CeAndS3
          Effect: Allow
          Action:
          - ce:*
          Resource: '*'
      Events:
        CostUsage:
          Type: Schedule # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Schedule: cron(30 2 1 * ? *)
            Name: cost-alert-schedule
            Description: cost alert schedule
            Enabled: True
